In [15]:
import sys
import math
import numpy as np
import itertools

from typing import List, Dict, Callable, Iterable, Tuple, Union

def max_index(values: List) -> tuple:
    max_value = max(values)
    max_index = values.index(max_value)
    return max_value, max_index
    
def max_common_subsequence(str_1: str, str_2: str) -> str:
    lenght = np.zeros((len(str_1)+1, len(str_2)+1), dtype=int)
    mmatrix = np.empty((len(str_1)+1, len(str_2)+1), dtype=str)

    for i in range(1, len(str_1)+1):
        for j in range(1, len(str_2)+1):
            if str_1[i-1] == str_2[j-1]:
                lenght[i, j] = 1 + lenght[i-1, j-1]
                mmatrix[i, j] = 'D'
            else:
                lenght[i, j] = max(lenght[i-1, j], lenght[i, j-1])
                ind = max_index((lenght[i-1, j], lenght[i, j-1]))
                mmatrix[i, j] = 'U' if ind else 'L'
    print(mmatrix)
    print(lenght)

    sp = ""
    while mmatrix[i, j] != '':
        if mmatrix[i, j] == 'D':
            i, j = i-1, j-1
            sp = str_1[i] + sp
        elif mmatrix[i, j] == 'U':
            j = j-1
        elif mmatrix[i, j] == 'L':
            i = i-1
        print(i, j)
    return sp

def LongestCommonString(str_1: str, str_2: str) -> set:
    #asignaciones
    l1 = len(str_1)
    l2 = len(str_2)
    matrix = [[0]*(l2+1) for x in range(l1+1)]
    longest = 0
    lcs_set = set()

    for i in range(l1):
        for j in range(l2):
            if str_1[i] == str_2[j]:
                #incrementa el contador en la posición diagonalmente inferior
                c = matrix[i][j] + 1
                matrix[i+1][j+1] = c
                if c > longest:
                    #si el contador es mayor que longest (tamaño de la cadena más larga) actualizamos el valor de longest
                    lcs_set = set()
                    longest = c
                    #añadimos la subcadena resultante en el conjunto
                    lcs_set.add(str_1[i-c+1:i+1])
                elif c == longest:
                    #si el contador es igual que longest únicamente añadimos la subcadena
                    lcs_set.add(str_1[i-c+1:i+1])
                    
    #print(matrix)
    return lcs_set
    #x = "bahamas"
    #y = "bananas"
    #LongestCommonString(x, y)

def edit_distance(str_1: str, str_2: str) -> int:
    distance = np.zeros((len(str_1)+1, len(str_2)+1), dtype=int)
    distance[0, 1:] = range(1, len(str_2)+1)
    distance[1:, 0] = range(1, len(str_1)+1)

    for i in range(1, len(str_1)+1):
        for j in range(1, len(str_2)+1):
            distance[i, j] = distance[i-1, j-1] if str_1[i-1] == str_2[j-1] else 1 + min(distance[i-1, j-1], distance[i-1, j], distance[i, j-1])

    print(distance)
    return distance[-1, -1]


In [16]:
x = 'forraje'
y = 'zarzajo'
max_common_subsequence(x,y)
LongestCommonString(x,y)
edit_distance(x,y)


[['' '' '' '' '' '' '' '']
 ['' 'U' 'U' 'U' 'U' 'U' 'U' 'U']
 ['' 'U' 'U' 'U' 'U' 'U' 'U' 'D']
 ['' 'U' 'U' 'D' 'U' 'U' 'U' 'U']
 ['' 'U' 'U' 'D' 'U' 'U' 'U' 'U']
 ['' 'U' 'D' 'U' 'U' 'D' 'U' 'U']
 ['' 'U' 'U' 'U' 'U' 'U' 'D' 'U']
 ['' 'U' 'U' 'U' 'U' 'U' 'U' 'U']]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 1 1 1 1 1]
 [0 0 0 1 1 1 1 1]
 [0 0 1 1 1 2 2 2]
 [0 0 1 1 1 2 3 3]
 [0 0 1 1 1 2 3 3]]
7 6
7 5
7 4
7 3
7 2
7 1
7 0
[[0 1 2 3 4 5 6 7]
 [1 1 2 3 4 5 6 7]
 [2 2 2 3 4 5 6 6]
 [3 3 3 2 3 4 5 6]
 [4 4 4 3 3 4 5 6]
 [5 5 4 4 4 3 4 5]
 [6 6 5 5 5 4 3 4]
 [7 7 6 6 6 5 4 4]]


4